### ISSUE TITLE
Only one dictionary edge case

### ISSUE THREAD

**Issue by itokatsu** [donkuri/lapis#21]
Yomitan doesn't format the same way when there is **only one** dictionary that has an entry for a word.
There's no list and no data-dictionary attribute; so the hiding function doesn't pick it up.
We get a card with primary definition and glossaries that look the same.

![image](https://github.com/user-attachments/assets/721da5dd-b1d3-421e-8d95-0f273b3e00cb)
![image](https://github.com/user-attachments/assets/60496604-72d9-4642-a58a-5b6321cbc688)

Steps to reproduce : 
1. Disable all but the dictionary defined for main-definition in yomitan.
2. Generate a card with yomitan
3. ???

I'm thinking it'd be better to not have the glossaries come up in such cases. Maybe detecting them by comparing html of both fields.

**Comment by bewizible** [comment]
@itokatsu 
> I'm thinking it'd be better to not have the glossaries come up in such cases. Maybe detecting them by comparing html of both fields.
I did try this quite a while ago, while I don't exactly remember the code I wrote, or the logic to it's nitty-gritties I remember failing because at times, the html contents don't exactly line up (one definition being wrapped in an extra <div> could be one example of this) but I'll take a look once more, if you have any code you could contribute I would really appreciate it!

@donkuri 
> ... but maybe that's annoying? @bewizible thoughts? 
A bit yes haha, but you're right in that this does let you know that that specific headword in question only had *one* dictionary, which is your main dictionary in this case. I'm a bit torn as to what to do this...

**Comment by bewizible** [comment]
Fixed! Thanks once again @itokatsu !!
