### ISSUE TITLE
Hint cards do not behave like described in the readme

### ISSUE THREAD

**Issue by itokatsu** [donkuri/lapis#22]
There's this one section in the readme.

| Field selected | Effect                                                                |
| -------------- | --------------------------------------------------------------------- |
| isHintCard     | Uses the `Hint` field to give you a hint in the front of the card     |
| isClickCard    | Makes the word in the front of the card clickable to get the sentence |
| isSentenceCard | The full sentence appears in the front instead of only the word       |

However `hint` is *always* displayed at the bottom of front side, regardless of card type.
Toggling `isHintCard` displays sentence alongside the word.

Not sure which is incorrect here.
I actually like the fact that just filling the `Hint` field shows it without having to also fill another field. In that sense `isHintCard` as described by the readme feels like a useless field to me.
But having word+sentence card named `isHintCard` is confusing.

**Comment by donkuri** [comment]
Oh that is interesting, I must have missed this when I first saw it. @bewizible

**Comment by bewizible** [comment]
Well then, this is intentional, it's also how JPMN names it so while making the card I didn't think much about this, but I think it is a bit unintuitive for a name.

>  In that sense isHintCard as described by the readme feels like a useless field to me.

@donkuri do you think it's useless? I mean, isn't Kaishi also formatted like this to begin with? And do you think we should change the name to `IsKaishiCard` for better understanding? Kaishi also is pretty well-known now

**Comment by St0wy** [comment]
Maybe to make it more descriptive it should be named `IsWordAndSentenceCard`. It's a bit long but it goes well with `IsSentenceCard` and can be understood by people who don't use/know Kaishi.

**Comment by donkuri** [comment]
I agree with St0wy, `IsWordAndSentenceCard` would make sense.

**Comment by donkuri** [comment]
Yeah, the way things are written makes it seem like `isHintCard` does something different, but always having the sentence on is more than just a hint. Maybe indeed having Hint cards like what you describe would be good. I think it wouldn't be too hard to write code that displays a hint if you click on it. Maybe a `<details>` tag?

**Comment by donkuri** [comment]
Yeah, my point is that having it called `isHintSentence` does do the same thing and actually makes sense with the rest of the kind of options we provide. I do not expect someone to create all their cards with it, just the ones they need. Does that not make sense?

**Comment by donkuri** [comment]
Well first of all, I think we need to rename `isHint...` into `isWordAndSentenceCard`. Then, we can open another issue for something like `showHint`.

**Comment by bewizible** [comment]
I fail to understand the need for `showHint`, if someone fills in the `Hint` field that should be it and it should just be displayed. The way I get it, we want the user to fill in `Hint` with whatever hint he wants to be displayed and then check `showHint` to _actually display the hint_ no? I think this is unnecessary, though we can rename `isHint...` into `isWordAndSentenceCard` but even that might not be necessary since, we do explain the field in the readme (which is wrong as of now but I'll fix it) and if people just don't read the readme then that's their choice, why do we bother with still making the card more _user-friendly_?

One more thing to realize here guys, the more releases we make with more fields/renamed fields the more it becomes a hassle for the user to upgrade, potentially leading to a case where they don't upgrade, so even if we only rename a field that would still require the user to change the notetype once more for ALL of their Lapis cards, leading them to having to completely re-upload their collections, which again, is a hassle and while people might do it once, doing this in a lot of releases might do more to deter them from upgrading, just one point of view I thought up.

**Comment by bewizible** [comment]
Actually, scratch some of my first paragraph I do think it is a good idea to rename the IsHintCard field, which is why I have renamed it, thanks a lot for the suggestions guys!

**Comment by bewizible** [comment]
Closing this PR because I'll rename IsHintCard in the new version, I dont see the point for the showHint field tho
