### ISSUE TITLE
Add a "Sentence Translation" field

### ISSUE THREAD

**Issue by St0wy** [donkuri/lapis#24]
When mining sentences that also have translation provided with them, it would be nice to be able to copy the translation into a "Sentence Translation" field.

For now I'm using "SelectionText" for this, but I then I can't use that for the selection text and I don't have the defition of the word I mined alongside the sentence translation.

**Comment by donkuri** [comment]
As you might have noticed, Lapis and other common Anki notetypes for immersion learning (JPMN, etc.) do not have a field for sentence translation. I will try to state a few reasons why this is so, and why Lapis will not support such a field either.

1. In the immersion community, Anki is viewed as a way to keep words fresh in your mind for when you next see them in immersion. It's also made to make it easier to read by avoiding a barrage of unknown words. This means that the sentences are auxiliary, and your main objective is retaining the readings of the word and some general, fuzzy sense of the word. This is because meaning is only constructed through actual immersion, so having explicitly set meanings in the translated sentences can be detrimental to getting a more general and accurate understanding of the word.
2. A large amount of Japanese media (anime, manga, novels, ...) have very questionable translations floating around on the internet. Beginners will not be able to discern what is correct from what is not, so we risk adding incorrect translations in the mix and making it harder to understand what's going on. Even if you find something that does have a translation like you mentioned, you usually cannot tell how accurate it is.
3. While it is somewhat fine in immersion to rely on translations made via DeepL or Google Translate provided you fact check them in some way, having a translation field in Lapis would encourage people to just auto-translate whatever they're not understanding and just plug it in Anki and take it as gospel. We already see this happen all the time with ChatGPT, where beginners will stop trying to understand what is going on and just blindly trust ChatGPT.
4. A big part of learning a new language is learning to deal with uncertainty. When you'll be talking with someone in real life, you usually won't have a dictionary or an assistant to help you say what you want to say. Similarly, when you start reading physical media (and you totally should, it's fun!) you will need to be able to construct readings and especially meanings from context. Relying too much on external translation makes it difficult to get used to the uncertainty that comes from a new piece of context in your target language.
5. Struggling with the language's weird quirks and grammar is what makes you actually learn it. In that sense, you should always first try to translate something yourself and then check your understanding against a valid translation. Anki is not the place for this. You should try to minimize your Anki time and maximize your immersion and/or output time instead.

Now of course, those reasons are all part of a specific framework, namely immersion learning (see [my guide](https://donkuri.github.io/learn-japanese/guide/#japanese-learning-guide) for an explanation of the method). If you specifically would like to have a translation field, do make one for your deck, but we will not explicitly support it in order to avoid the common pitfalls listed above.

**Comment by St0wy** [comment]
Thanks for the explanation, to maybe state my intentions more clearly, I proposed that because I really like the Tango decks (although they sometimes present some words too early), especially with their N+1 structure. These decks have the sentence translation, and the translation of the word in the back.

Then I don't see how point 1 is an argument against having the sentence translation, it doesn't prevent to focus on training the reading of a word, it just adds the option to see if you kinda understood the same thing as the translation. For point 2-5, I'm using this with translations from a grammar book, that I assumed has been checked by someone who knows how to do it correctly, so I think it could still be usefull in that context ?

But I totally agree with the rest of your points, that with a bad translation, which include most of the ones available, it's not very usefull (and I already read your guide haha).

But thanks again for explaining why!

**Comment by donkuri** [comment]
The issue is that the mental load that comes with checking your understanding in Anki makes it both slower and harder to do, thus leading to more time spent on Anki and less time spent actually immersing. Even with a grammar book, you should always check the book's translations yourself, and make sure they aren't garbage, because various Japanese grammar resources are notoriously bad (we can discuss it in private if you would like). 

If you specifically want to train grammar in Anki (I am not a fan but I see why people would do it), then yeah I would modify the deck, but just to clarify, Lapis is not meant to make premade decks but is really made to help people mine, so in this sense you usually do not mine stuff you already have a translation for. Regardless, this is kinda whatever, if you want a translation field do make one for yourself. :)
