### ISSUE TITLE
Show kanji on hover

### ISSUE THREAD

**Issue by Taisaka37** [donkuri/lapis#28]
Hey, I really liked JPMN because I could hover over a kanji in the word and it would show me that kanji and its reading in all my other anki cards, is that not possible on lapis?
<img width="1503" alt="Screenshot 2024-12-16 at 13 34 16" src="https://github.com/user-attachments/assets/2ed346e2-2c0e-461f-b133-ff44b7c44bbc" />

**Comment by donkuri** [comment]
This unfortunately requires a lot of Javascript which poses two problems:

1. We need someone that knows how to implement this.
2. It needs to be implemented in such a way that it is still fast, especially on mobile.

As such, I don't think it will be implemented any time soon, but if anyone wants to have a go at it, why not!

**Comment by bewizible** [comment]
Yes, the reasons are exactly the same as @donkuri mentions, I personally worked on developing the card and tried to model it as closely to JPMN as I could, but the kanji hover was practically impossible to implement because of how all of JPMN's code is machine generated, and even if I did find a way to extract that code and put it (from the source code of JPMN) I think it would lead to a lot of bugs and potentially degrade performance. So it's pretty hard for me to say if or when this would get implemented, but maybe we should leave these issues open @donkuri so that someone (hopefully) stumbles upon these, someone who knows how this could be done haha.
