### ISSUE TITLE
iOS support

### ISSUE THREAD

**Issue by donkuri** [donkuri/lapis#3]
Currently, the notetype doesn't seem to be supported on iOS for some reason. More specifically:

1. The background on dark mode is off (it's a sort of off-white instead of being the standard dark background), maybe it is also off on light mode but I have no way to check without an iOS device.
2. The switching between dictionaries on the left and right are troublesome and seem only to work after holding for a bit, which tends to do something else.

In order to fix this, we would need an iOS device to debug things, or another dev with such a device and ideally some experience with iOS.

**Comment by YonKuma** [comment]
1. The background on light mode is currently working. The issue with the dark mode background seems to be the `--canvas` variable not giving the same result as it does on desktop (though I'm not 100% positive on that since the debugging tools aren't as good on iOS).
2. Fix to this is to add the lines `leftEdge.classList.add("tappable");` and `rightEdge.classList.add("tappable");` where leftEdge and rightEdge are defined (around 370 in my code). Otherwise iOS causes issues trying to interpret taps as gestures (seems like there are issues whether or not gestures are set in those particular areas).

**Comment by donkuri** [comment]
Do you have an idea how we could get around the `--canvas` issue for iOS? I could distribute a separate version of the deck for iOS, unless we can force iOS/Android in the Styling option.

**Comment by mcgrizzz** [comment]
A good temporary solution I've implemented is to just manually define `--canvas` for iphone and ipad in night mode. 

```
.iphone .nightMode,
.ipad .nightMode {
	--canvas: #2c2c2c;
}
```

**Comment by YonKuma** [comment]
Tbh, I feel like that's a fine long term solution. If `--canvas` ever ends up being used in light mode, a similar patch can be made. It's not like it'll cause technical debt to build, there are only those two possible values to patch.

**Comment by bewizible** [comment]
I'll try to implement both of these in the card, and see how it goes!

**Comment by stexus** [comment]
I've been using both mcgrizzzz's and YonKuma's solution and I don't notice any oddities at all I think (both light/dark modes)! Might be stable enough to consider merging into main. I primarily review on iOS.

**Comment by donkuri** [comment]
Added in the latest release, thanks everyone!
