### ISSUE TITLE
A way to decrease the size of furigana

### ISSUE THREAD

**Issue by Skretkowicz** [donkuri/lapis#34]
On some of the words, furigana is so large, it makes the words look weird and spaced out, is there a way to decrease it? (I read the Guide and found the different font sizes in Styling but I do not see any that corresponds to furigana)

<img width="698" alt="image" src="https://github.com/user-attachments/assets/394b191a-359b-42f1-9ae2-40356134a8a3" />

**Comment by donkuri** [comment]
The words are spaced out because, well, you need enough space to write out the entire word. As you can see, 状況 is a lot smaller to write than じょうきょう, so there is not a lot you can do. Also, this is not managed by Lapis but rather by AJT Japanese and Anki itself directly, since we are using `{{furigana:SomeFuriganaField}}`.

Since this has nothing to do with Lapis proper (as far as I know), I will close this issue. If you do make an issue on Anki, please do link the issue here.
